services:
    youtrack:
        image: jetbrains/youtrack:2026.1.12848
        volumes:
            - ./tests/data/youtrack/2026-1-12848/data:/opt/youtrack/data
            - ./tests/data/youtrack/2026-1-12848/conf:/opt/youtrack/conf

        ports:
            - '8080:8080'
